### ISSUE TITLE
[API/Website] OAuth

### ISSUE THREAD

**Issue by zyunlam** [ISSUIUC/Spaceshot-AV#13]
[This](https://github.com/ISSUIUC/ISS_HILSIM/blob/AV-1121-kamaji-web-improvements/Central-Server/API/internal/auth.py#L8) contains incomplete code for authenticating if a member is part of the ISSUIUC organization. 

**Tasks:**
- [ ]  Add in a URL that redirects to Github to authenticate the user
- [ ] Check if the user is part of the ISSUIUC organization
- [ ] If the user is not part of the ISSUIUC organization redirect them to an error page
- [ ] Add an API endpoint to check if the user has been authenticated

**Possible useful resources:**
<https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps>
<https://docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#check-organization-membership-for-a-user>

**Comment by zyunlam** [comment]
You want to fix this function https://github.com/ISSUIUC/ISS_HILSIM/blob/main/Central-Server/API/internal/auth.py#L5-L8
